# Generated by Django 5.1.6 on 2025-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_shoppingcart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
