# Generated by Django 5.1.6 on 2025-05-05 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_stuff_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
