# Generated by Django 5.1.6 on 2025-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(default=255, max_length=254, unique=True)),
                ('fav_toy', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
