# Generated by Django 5.1.6 on 2025-04-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_and_migrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoITeeens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('b', 'Buy'), ('s', 'Sell'), ('с', 'Change'), ('r', 'Rent')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=18, unique=True),
        ),
    ]
